### ISSUE TITLE
Version required is wrong, 3.5 features in use in JSONModelRelation

### ISSUE THREAD

**Issue by pobocks** [archivesspace-labs/ArchivesSnake#12]
Currently setup.py claims that we're useavle on 3.4+, but I used dict splatting in literals, which hit in 3.5, and didn't catch it bc I use 3.6 to develop.

We should either rewrite that line to use dict.update, or specify 3.5 as min version; given the age of 3.4, I'd be inclined to latter, but I know there's a lot of old Python installs, and Red Hat's antique sensibilities, etc.

**Comment by gwiedeman** [comment]
Generally, I'm inclined to support the broadest amount of environments that are relatively feasible. I think ASnake in particular will potentially be used by people without a ton of Python skills, and setting up environments generally is a huge barrier. If people don't realize they're on 3.4, this could be a problematic issue for them to troubleshoot.

That said, I'm not sure how realistic that is, and supporting older versions shouldn't undermine maintenance. I'm not sure how prevalent 3.4 is, looks like Ubuntu 14.04 has it but 16.04 has 3.5.

In this case, if its just changing one line to support 3.4, I say do it, but I'd also expect to revisit that if it comes up again in a more problematic case.

**Comment by pobocks** [comment]
I changed the code back. Need to test it on 3.4, but I don't think I used anything else not in it.
