### ISSUE TITLE
Add helper functions?

### ISSUE THREAD

**Issue by helrond** [archivesspace-labs/ArchivesSnake#28]
When interacting with the AS API, I often find myself writing functions to return things like dates, note content, or instance information. I'm wondering if it would be worth considering adding some of those to ASnake as a separate module? Or is this scope creep?

**Comment by pobocks** [comment]
So, I definitely think there's a space for adding broader utility functions to ASnake (or as a complementary project, something like asnake.contrib as a separate package) but I think we do want to be somewhat selective in deciding what is generic functionality and what is "a specific thing I personally do regularly?"

I definitely think there's stuff that's going to be apropriate to do as helper functions, for sure - if you wanted to spec out some examples or just point me at some code, I'll look it over and then we can talk about this and maybe solicit broader feedback about what people see as needs?

**Comment by helrond** [comment]
OK, sounds good - let me work on putting together a list + code examples. Off the top of my head, I think a `display()` helper that returns human-readable strings for objects that don't already have them (like dates) could be generically useful. I think there's also probably some way of handling all the variations of note content that could be generalized.

**Comment by pobocks** [comment]
Poking this bc I think it's valuable and I don't know if you're still thinking of doing it!

**Comment by helrond** [comment]
Hi, sorry, as usual more urgent 🔥needed to be extinguished. This is still something I'd like to do, but I'm thinking of analyzing what we've got [here](https://github.com/RockefellerArchiveCenter/scripts/tree/master/archivesspace) to see if some patterns emerge. It's probably gonna take me a bit to get to that though.

**Comment by helrond** [comment]
Closing this as we've now merged utils into core!
