### ISSUE TITLE
Add example for aliases

### ISSUE THREAD

**Issue by p-galligan** [archivesspace-labs/ArchivesSnake#3]
I think it could be helpful to provide a link for how to create an alias in the readme.

"Note that this assumes your install of Python has python3 and pip3 aliases, which it should, especially if installed in a virtualenv."

Above could be obtuse for some.

**Comment by pobocks** [comment]
Fixed in 2cc0a71a599322973ef3af7c313c1fa499723674 by changing language to be less specific and suggest checking out docs.
