### ISSUE TITLE
.tree on an archival_object returns an error

### ISSUE THREAD

**Issue by gwiedeman** [archivesspace-labs/ArchivesSnake#32]
Calling .tree on an archival_object that does not have children raises an error: 
```
AttributeError: '#<archival_object:/repositories/2/archival_objects/225759>' has no attribute or route named 'tree'
```
I think its here: https://github.com/archivesspace-labs/ArchivesSnake/blob/3c5eb6aa97398c5377c1c7fbd67c78ed406776fb/asnake/jsonmodel/__init__.py#L170

For resources without children, there's still a tree, so `len(resource.tree.children)` returns `0`, but `if collection.tree` seems to always return `True`, which may also not be ideal.

My first reaction would be to make .tree return `False` if there's no children for both resources and archival objects, but I'm not sure if there's anything useful in child-less resource trees that wouldn't be accessible. Having child-less archival objects return an empty list for .tree.children would also be functional, but I dunno what .tree would return and they both should be consistent.

**Comment by pobocks** [comment]
I'm not sure what's going on, but I just tested this locally on a childless AO and it didn't fail?

`x.repositories(24).archival_objects(2909918).tree.json()`

```javascript
{
 'title': 'Hesperia (detail) : black chalk or pencil drawing in black chalk or pencil on paper, 1676',
 'id': 2909918,
 'record_uri': '/repositories/24/archival_objects/2909918',
 'publish': True,
 'suppressed': False,
 'node_type': 'archival_object',
 'level': 'item',
 'instance_types': ['graphic_materials'],
 'has_children': False,
 'children': [],
 'containers': []
}
```

I'm wondering if Is there another characteristic of the AO that's causing this?
