### ISSUE TITLE
Walk_tree function in utils is not working

### ISSUE THREAD

**Issue by bonniegee** [archivesspace-labs/ArchivesSnake#39]
When using the `walk_tree` function from the `utils` in .9, the following error is thrown:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/asnake/utils/__init__.py", line 326, in walk_tree
    uri = resolve_to_uri(thingit, client)
TypeError: resolve_to_uri() takes 1 positional argument but 2 were given
```

It looks like [this is the relevant line](https://github.com/archivesspace-labs/ArchivesSnake/blob/29507b93680c1045431f40e97d46ec7ca93890bb/asnake/utils/__init__.py#L326), and that "client" needs to be removed from calling the function.

**Comment by pobocks** [comment]
Ah, yeah. Good catch!  Do you wanna submit the PR or should I?

**Comment by bonniegee** [comment]
I can take a stab at it--PR incoming...
